name: demucs-api
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - ffmpeg>=4.2
  - pytorch>=1.8.1
  - torchaudio>=0.8
  # - cudatoolkit=10.2
  - cpuonly
  - tqdm>=4.36
  - fastapi>=0.77.1
  - uvicorn>=0.17.6
  - pydantic>=1.9.0
  - tomlkit>=0.10.2
  - python-multipart
  - pip:
      - demucs>=3,<4
