steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
    # env:
    #   - "PUBLIC_FIREBASE_API_KEY=$${PUBLIC_FIREBASE_API_KEY}"
    secretEnv: ["PUBLIC_FIREBASE_API_KEY"]
  - name: gcr.io/demucs-service/firebase
    args: ["deploy", "--project=demucs-service", "--only=hosting"]
availableSecrets:
  secretManager:
    - versionName: projects/demucs-service/secrets/FIREBASE_API_KEY/versions/1
      env: "PUBLIC_FIREBASE_API_KEY"
