version: "3"

tasks:
  run-api:
    dir: model/src
    cmds:
      - uvicorn api:app --host 0.0.0.0 --port 8080 --reload

  image:
    dir: model
    cmds:
      - docker build -t demucs-api .

  docker-run:
    dir: model
    cmds:
      - docker run -it -p 8080:8080 demucs-api

  image-push:
    dir: model
    cmds:
      - docker tag demucs-api us-central1-docker.pkg.dev/demucs-service/demucs-api/demucs-api
      - docker push us-central1-docker.pkg.dev/demucs-service/demucs-api/demucs-api
