site_name: DEMUCS service
site_dir: ../dist/docs

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
